### ISSUE TITLE
레이텍 문법 오류

### ISSUE THREAD

**Issue by Greathoney** [yh08037/gnbai20201#19]
![image](https://user-images.githubusercontent.com/44860482/79441314-07fcdc00-8012-11ea-91ce-7cd9f2c05248.png)

@yh08037 

과제를 하는 과정에서 오른쪽 그림 처럼 되어야 하는데 왼쪽 그림처럼 문법이 정상적으로 인식이 되지 않습니다.

이걸 이렇게 하면 되는것 같은데 확인 부탁드려요

~~~
    $\theta^*=\left(x^Tx+\lambda
   \begin{bmatrix}
      0 & 0 & \cdots & 0 \\
      0 & 1 & \cdots & 0 \\
      \vdots & \vdots & \ddots & \vdots \\
      0 & 0 & \cdots & 1 \\
   \end{bmatrix}
    \right)^{-1}x^Ty$
~~~

**Comment by dohun-qml** [comment]
@Greathoney 

기존의 코드도 Colab 환경에서는 제대로 수식이 표현되어서 단지 Github의 ipynb 인코딩에 문제가 있다고 생각했었는데, 해결방법이 있었군요. 새로운 tex코드 확인하였습니다. 수정해주셔서 감사합니다. Pull request에 수정사항이 반영되어있는 것을 확인하였고, 원본 레포지터리에 적용하였습니다. 앞으로도 좋은 피드백 부탁드립니다!
